name: Build iOS

on:
  push:
    branches:
      - '*'

jobs:
  build:
    name: Build iOS
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Behaviour Test Plan
        run: |
           set -o pipefail && xcodebuild -project RangeUISlider.xcodeproj -scheme RangeUISlider clean test -testPlan BehaviourTestPlan CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -destination 'platform=iOS Simulator,name=iPhone 8,OS=latest' | xcpretty
      - name: Programmatic Changes Test Plan
        run: |
           set -o pipefail && xcodebuild -project RangeUISlider.xcodeproj -scheme RangeUISlider clean test -testPlan ProgrammaticChangesTestPlan CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -destination 'platform=iOS Simulator,name=iPhone 8,OS=latest' | xcpretty
      - name: Right To Left Test Plan
        run: |
           set -o pipefail && xcodebuild -project RangeUISlider.xcodeproj -scheme RangeUISlider clean test -testPlan RightToLeftTestPlan CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -destination 'platform=iOS Simulator,name=iPhone 8,OS=latest' | xcpretty
      - name: Build iOS Demo
        run: |
           set -o pipefail && xcodebuild -project RangeUISlider.xcodeproj -scheme RangeUISliderDemo clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -destination 'platform=iOS Simulator,name=iPhone 8,OS=latest' | xcpretty
      - name: Build SPM demo
        run: |
           set -o pipefail && xcodebuild -project DemoSPM.xcodeproj -scheme DemoSPM  clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -destination 'platform=iOS Simulator,name=iPhone 8,OS=latest' | xcpretty
